//Developement and IT
const DevelopementITPopular = [
  " JavaScript Developers",
  "Web Designers",
  "WordPress Developers",
  "HTML Developers",
  "CSS Developers",
  "PHP Developers",
  "Python Developers",
  "Android Developers",
  "Shopify Developers",
  "Landing Page Specialists",
  "API Integration Freelancers",
  "HTML5 Developers",
  "React.js Developers",
  "Java Developers",
  "Node.js Developers & Programmers",
  "Web Application Freelancers",
  "Mobile App Developers",
  "MySQL Developers",
  "Android App Developers",
  "Woocommerce Developers",
];
const DevelopementITRoles = [
  "AngularJS Developers",
  "AWS Developers",
  "C# Developers",
  "C++ Developers",
  "CSS Developers",
  "Data Analysts",
  "Data Visualization Consultants",
  "Developers",
  "DevOps Engineers",
  "eCommerce Developers",
  "Front End Developers",
  "Full Stack Developers",
  "Game Developers",
  "Golang Developers",
  "HTML5 Developers",
  "Machine Learning Engineers",
  "Magento Developers",
  "Mobile App Developers",
  "MySQL Developers",
  "Python Developers",
  "React Native Developers",
  "Ruby Developers",
  "Ruby on Rails Developers",
  "Rust Developers",
  "Scala Developers",
  "Shopify Developers",
  "Software Developers",
  "Software QA Testers",
  "Unity 3D Developers",
  "Vue JS Developers",
  "Web Developers",
  "WordPress Developers",
];
const DevelopementITCrossFunctionalRoles = [
  "2D Animators",
  "3D Designers",
  "Amazon FBA Specialists",
  "Conversion Rate Optimizers",
  "Copywriters",
  "Data Entry Specialists",
  "Data Scrapers",
  "Database Programmers",
  "Digital Marketers",
  "Graphic Designers",
  "Microsoft Access Consultants",
  "Network Engineers",
  "Power BI Consultants",
  "Product Managers",
  "Product Marketers",
  "Project Managers",
  "Salesforce App Developers",
  "SEO Experts",
  "Tableau Experts",
  "Translators",
  "UI Designers",
  "UX Designers",
  "Web Designers",
];
const DevelopementITProjects = [
  "Chatbot Services",
  "Cybersecurity & Data Protection Services",
  "Data Analysis & Report Services",
  "Database Services",
  "Desktop Application Services",
  "Development for Streamer Services",
  "eCommerce Development Services",
  "File Conversion Services",
  "Game Development Services",
  "Mobile App Development Services",
  "Online Coding Lessons",
  "QA Services",
  "Support & IT Services",
  "User Testing Services",
  "Web Programming Services",
  "Website & CMS Software Services",
  "WordPress Development Services",
];
const AllDevelopmentIT = DevelopementITPopular.concat(DevelopementITRoles)
  .concat(DevelopementITCrossFunctionalRoles)
  .concat(DevelopementITProjects);

// Design and Creative
const DesignCreativePopular = [
  "Graphic Designers",
  "Adobe Photoshop Experts",
  "Adobe Illustrator Experts",
  "Video Editors",
  "Logo Designers",
  "Illustrators",
  "Video Producers",
  "Adobe After Effects Specialists",
  "Animators",
  "Brand Identity & Guidelines Freelancers",
  "Photo Editors",
  "Adobe Premiere Pro Specialists",
  "Video Post Editing Specialists",
  "Adobe InDesign Experts",
  "Print Designers",
  "Infographic Designers",
  "Motion Graphics Designers",
  "Videographers",
  "Audio Editors",
  "2D Animators",
];
const DesignCreativeRoles = [
  "2D Animators",
  "2D Designers",
  "2D Game Artists",
  "3D Animators",
  "3D Designers",
  "3D Modelers",
  "Adobe After Effects Experts",
  "Adobe Illustrator Experts",
  "Adobe InDesign Experts",
  "Adobe Photoshop Experts",
  "Animators",
  "Audio Engineers",
  "Audiobook Narrators",
  "Banner Designers",
  "Book Cover Designers",
  "Brand Strategists",
  "Brochure Designers",
  "Business Card Designers",
  "Caricature Artists",
  "Flyer Designers",
  "Infographic Designers",
  "Instructional Designers",
  "Logo Designers",
  "Mobile UI Designers",
  "Packaging Designers",
  "Photo Editors",
  "Photo Retouchers",
  "Photographers",
  "Podcasting Freelancers",
  "Poster Designers",
  "T-Shirt Designers",
  "Video Producers",
];
const DesignCreativeProjects = [
  "3D Product Animation Services",
  "App & Website Promo Videos Services",
  "AR Filters & Lenses Services",
  "Architecture & Interior Design Services",
  "Banner Ad Services",
  "Book Design Services",
  "Brand Style Guide Services",
  "Building Information Modeling Services",
  "Business Cards & Stationery Design Services",
  "Cartoons & Comics Services",
  "Character Animation Services",
  "Character Modeling Services",
  "Flyer Design Services",
  "Game Design Services",
  "Graphics for Streamers Services",
  "Illustration Services",
  "Industrial & Product Design Services",
  "Infographic Design Services",
  "Landscape Design Services",
  "Logo Animation Services",
  "Logo Design Services",
  "Packaging Design Services",
  "Pattern Design Services",
  "Photoshop Editing Services",
  "Podcast Cover Art Services",
  "Portraits & Caricatures Services",
  "Presentation Design Services",
  "Product Photography Services",
  "Resume Design Services",
  "Social Media Design Services",
  "T-Shirts & Merchandise Design Services",
  "Web & Mobile Design Services",
];
const AllCreativeDesign = DesignCreativePopular.concat(
  DesignCreativeRoles
).concat(DesignCreativeProjects);

//Sales & Marketing
const SalesMarketingPopular = [
  "Social Media Marketers",
  "Facebook Freelancers",
  "SEO Experts",
  "Instagram Marketers",
  "Lead Generation Experts",
  "Instagram Freelancers",
  "Social Media Managers",
  "Marketing Strategists",
  "Google Analytics Experts",
  "Facebook Ad Campaign Freelancers",
  "Facebook Ads Specialists",
  "Instagram Ad Campaign Freelancers",
  "Email Marketers",
  "SEO Keyword Researchers",
  "Internet Marketers",
  "Campaign Managers",
  "Cold Callers",
  "Influencer Marketers",
  "Conversion Rate Optimizers",
  "Telemarketers",
];
const SalesMarketingRoles = [
  "Adwords Experts",
  "Affiliate Marketers",
  "Amazon SEO Experts",
  "Blog Writers",
  "Content Marketers",
  "Digital Marketers",
  "Email Marketers",
  "Email Marketing Consultants",
  "Facebook Marketers",
  "Google Analytics Consultants",
  "Google Tag Managers",
  "Instagram Marketers",
  "Internet Marketers",
  "Lead Generators",
  "Link Builders",
  "Mailchimp Freelancers",
  "Marketing Automation Experts",
  "Marketing Consultants",
  "Marketing Strategists",
  "Pinterest Marketers",
  "PPC Specialists",
  "Search Engine Marketers",
  "SEO Audit Freelancers",
  "SEO Experts",
  "Social Media Managers",
  "Social Media Marketers",
  "Telemarketers",
  "Yoast SEO Freelancers",
  "YouTube Marketers",
];
const SalesMarketingCrossFunctional = [
  "Amazon Seller Central Experts",
  "App Designers",
  "BigCommerce Developers",
  "Blog Writers",
  "Brand Managers",
  "Cold Callers",
  "Data Entry Specialists",
  "Editors",
  "Explainer Video Freelancers",
  "Full Stack Developers",
  "Game Developers",
  "Google Cloud Platform Freelancers",
  "Google Data Studio Experts",
  "Graphic Designers",
  "HubSpot Freelancers",
  "Infographic Designers",
  "Internet Researchers",
  "Microsoft Excel Experts",
  "Microsoft Word Experts",
  "PHP Developers",
  "Presentation Designers",
  "Project Managers",
  "Shopify Developers",
  "Spreadsheet Experts",
  "Squarespace Developers",
  "Virtual Assistants",
  "Web Developers",
  "Web Scrapers",
  "Webflow Freelancers",
  "WooCommerce Developers",
  "WordPress Developers",
];
const SalesMarketingProjects = [
  "Book & eBook Marketing Services",
  "Content Marketing Services",
  "Crowdfunding Services",
  "Domain Research Services",
  "eCommerce Marketing Services",
  "Email Marketing Services",
  "Influencer Marketing Services",
  "Lead Generation Services",
  "Local SEO Services",
  "Market Research Services",
  "Marketing Strategy Services",
  "Mobile Marketing & Advertising Services",
  "Music Promotion Services",
  "Podcast Marketing Services",
  "Public Relations Services",
  "SEM Services",
  "SEO Services",
  "Social Media Advertising Services",
  "Social Media Management Services",
  "Survey Services",
  "Video Marketing Services",
  "Web Analytics Services",
  "Web Traffic Optimization Services",
];
const AllSalesMarketing = SalesMarketingPopular.concat(SalesMarketingRoles)
  .concat(SalesMarketingCrossFunctional)
  .concat(SalesMarketingProjects);

//Writing & Translation
const WritingTranslationPopular = [
  "Chatbot Services",
  "Cybersecurity & Data Protection Services",
  "Data Analysis & Report Services",
  "Database Services",
  "Desktop Application Services",
  "Development for Streamer Services",
  "eCommerce Development Services",
  "File Conversion Services",
  "Game Development Services",
  "Mobile App Development Services",
  "Online Coding Lessons",
  "QA Services",
  "Support & IT Services",
  "User Testing Services",
  "Web Programming Services",
  "Website & CMS Software Services",
  "WordPress Development Services",
];
const WritingTranslationRoles = [
  "Academic Writers",
  "Article Writers",
  "Biography Writers",
  "Blog Writers",
  "Business Plan Writers",
  "Business Writers",
  "Comedy Writers",
  "Content Writers",
  "Copy Editors",
  "Copywriters",
  "Cover Letter Writers",
  "eBook Writers",
  "Essay Writers",
  "Fact Checkers",
  "Fashion Writers",
  "Fiction Writers",
  "Legal Writers",
  "Lyrics Writers",
  "Medical Writers",
  "Online Writers",
  "Press Release Writers",
  "Proposal Writers",
  "RFP Writers",
  "Report Writers",
  "Research Paper Writers",
  "Resume Writers",
  "Sales Writers",
  "Scientific Writers",
  "Screenwriters",
  "SEO Writers",
  "Speech Writers",
  "Technical Writers",
  "Travel Writers",
  "White Paper Writers",
];
const WritingTranslationCrossFunctional = [
  "Amazon SEO Experts",
  "Audiobook Narrators",
  "Book Cover Designers",
  "Call Center Agents",
  "Childrens Book Illustrators",
  "Data Entry Specialists",
  "Digital Marketers",
  "Email Marketers",
  "Excel Experts",
  "Fashion Designers",
  "Graphic Designers",
  "Internet Researchers",
  "Microsoft Office Specialists",
  "Microsoft Word Experts",
  "Podcasting Freelancers",
  "PowerPoint Experts",
  "Project Managers",
  "Research Assistants",
  "Sales Representatives",
  "SEM Specialists",
  "Social Media Managers",
  "Transcriptionists",
  "Twitter Marketers",
  "Video Editors",
  "Video Producers",
  "Virtual Assistants",
  "Wikipedia Specialists",
  "Zoom Video Specialists",
];
const WritingTranslationProjects = [
  "Article & Blog Post Services",
  "Beta Reading Services",
  "Book & eBook Writing Services",
  "Book Editing Services",
  "Brand Voice & Tone Services",
  "Business Names & Slogan Services",
  "Case Study Services",
  "Cover Letter Services",
  "Creative Writing Services",
  "Email Copy Services",
  "Grant Writing Services",
  "Legal Writing Services",
  "LinkedIn Profile Services",
  "Localization Services",
  "Online Language Lessons",
  "Podcast Writing Services",
  "Press Release Services",
  "Product Description Services",
  "Proofreading & Editing Services",
  "Research & Summary Services",
  "Resume Writing Services",
  "Sales Copy Services",
  "Scriptwriting Services",
  "Social Media Copy Services",
  "Speechwriting Services",
  "Technical Writing Services",
  "Transcript Services",
  "Translation Services",
  "UX Writing Services",
  "Website Content Services",
  "White Paper Services",
];
const AllWritingTranslation = WritingTranslationPopular.concat(
  WritingTranslationRoles
)
  .concat(WritingTranslationCrossFunctional)
  .concat(WritingTranslationProjects);

//Admin And Customer
const AdminCustomerPopular = [
  "Internet Researchers",
  "Data Entry Specialists",
  "Virtual Assistants",
  "Customer Service Representatives",
  "Administrative Assistants",
  "Email Handlers",
  "Appointment Setters",
  "Data Scrapers",
  "Customer Support Representatives",
  "Project Managers",
  "File Management Freelancers",
  "Call Center Agents",
  "Chat Support Specialists",
  "Email Support Freelancers",
  "Interpersonal skills Freelancers",
  "Google Docs Experts",
  "Scheduling Freelancers",
  "Canva Graphic Designer",
  "Microsoft Word Experts",
  "Phone Support Agents",
];
const AdminCustomerRoles = [
  "Administrative Assistants",
  "Appointment Setters",
  "Bookkeepers",
  "Customer Service Representatives",
  "Customer Support Representatives",
  "Data Entry Specialists",
  "Data Miners",
  "Editors",
  "Email Handlers",
  "Microsoft Excel Experts",
  "Executive Assistants",
  "Google Docs Experts",
  "Google Sheets Experts",
  "Google Slides Experts",
  "Graphic Designers",
  "HTML Developers",
  "Internet Researchers",
  "Intuit QuickBooks Specialists",
  "Microsoft Office Specialists",
  "Microsoft Outlook Specialists",
  "Microsoft Word Experts",
  "Personal Assistants",
  "PowerPoint Experts",
  "Project Managers",
  "Proofreaders",
  "Recruiters",
  "Research Assistants",
  "Social Media Managers",
  "Transcriptionists",
  "Typists",
  "Virtual Assistants",
  "Cold Callers",
];
const AdminCustomerCrossFunctional = [
  "Social Media Marketers",
  "Adobe Photoshop Experts",
  "Blog Writers",
  "Creative Writers",
  "Excel VBA Developers",
  "Writers",
  "Financial Analysts",
  "Musical Composition Specialists",
  "Press Release Writers",
  "Wikipedia Specialists",
  "Zoom Video Conferencing Specialists",
  "YouTube Marketers",
  "Paralegal Professionals",
  "Etsy Administration Specialists",
  "Lead Generation Specialists",
  "Sales Representatives",
  "Pitch Deck Writers",
  "HubSpot Specialists",
  "Web Scrapers",
  "LinkedIn Specialists",
  "Real Estate Virtual Assistants",
  "Smartsheet Specialists",
  "Tax Preparers",
  "Zendesk Specialists",
  "Chatbot Developers",
  "Presentation Designers",
  "Legal Researchers",
  "PDF Converters",
];
const AdminCustomerProjects = [
  "Project Management Services",
  "Virtual Assistant Services",
  "Data Entry Services",
  "eCommerce Management Services",
  "Flyer Distribution Services",
  "Business Consulting Services",
  "Business Plan Services",
  "Financial Consulting Services",
  "HR Consulting Services",
  "Legal Consulting Services",
];
const AllAdminCustomer = AdminCustomerPopular.concat(AdminCustomerRoles)
  .concat(AdminCustomerCrossFunctional)
  .concat(AdminCustomerProjects);

//Finance And Accounting
const FinanceAccountingPopular = [
  "Accountants",
  "Bookkeepers",
  "Business Planners",
  "Financial Analysts",
  "Business Analysts",
  "Bank Reconciliation Specialists",
  "Tax Preparers",
  "QuickBooks Consultants",
  "Financial Accountants",
  "Business Intelligence Developers",
  "Certified Public Accountants",
  "Tax Law Lawyers & Legal Professionals",
  "Account Reconciliation Specialists",
  "Financial Modelers",
  "Fundraising Consultants",
  "Xero Specialists",
  "Startup Consultants",
  "Communication skills Freelancers",
  "General Ledger Specialists",
  "Accounts Receivable Management",
];
const FinanceAccountingRoles = [
  "Accountants",
  "Accounts Payable Managers",
  "Bookkeepers",
  "Intuit QuickBooks Specialists",
  "Business Consultants",
  "Civil Law Lawyers & Legal Professionals",
  "Consultants",
  "Contract Law Legal Professionals",
  "CPAs",
  "Data Entry Specialists",
  "Excel Experts",
  "Financial Analysts",
  "Financial Managers",
  "Financial Reporting Analysts",
  "Intellectual Property Law Professionals",
  "Intuit TurboTax Specialists",
  "Market Research Analysts",
  "Payroll Processing Specialists",
  "Project Managers",
  "Legal Advisors",
  "Business Analysts",
  "Business Development Specialists",
  "Financial Accountants",
  "Financial Forecasting Specialists",
  "Financial Modelers",
  "Tax Preparers",
  "Forex Traders",
  "Spreadsheet Experts",
  "Financial Planners",
  "Wave Accounting Specialists",
];
const FinanceAccountingCrossFunctional = [
  "Human Resource Managers",
  "Email Marketers",
  "Virtual Assistants",
  "Social Media Consultants",
  "Sales Consultants",
  "SEO Experts",
  "Creative Writers",
  "Customer Service Representatives",
  "Data Entry Specialists",
  "Strategic Planning Specialists",
  "Usability Testing Specialists",
  "Startup Consultants",
  "Regression Testers",
  "Recruiters & Recruitment Consultants",
  "MySQL Programmers",
  "PowerPoint Experts",
  "Microsoft Word Experts",
  "Marketing Strategists",
  "Translators",
  "Google Spreadsheet Experts",
  "Microsoft Power BI Consultants",
  "Legal Consultants",
  "Business Plan Writers",
  "Legal Researchers",
  "Xero Experts",
  "Business Coaches",
  "Corporate Law Professionals",
];
const FinanceAccountingProjects = [
  "Business Consulting Services",
  "Business Plan Services",
  "Financial Consulting Services",
  "HR Consulting Services",
  "Legal Consulting Services",
];
const AllFinanceAccounting = FinanceAccountingPopular.concat(
  FinanceAccountingRoles
)
  .concat(FinanceAccountingCrossFunctional)
  .concat(FinanceAccountingProjects);

//Legal
const LegalPopular = [
  "Legal Consultants",
  "Contract Law Lawyers & Legal Professionals",
  "Legal Researchers",
  "Contract Drafters",
  "Paralegals Professionals",
  "Corporate Law Lawyers & Legal Professionals",
  "Legal Assistance Specialists",
  "Intellectual Property Law Lawyers & Legal Professionals",
  "Partnership Agreements Freelancers",
  "Trademark Consultants",
  "Business Law Freelancers",
  "Patent Law Lawyers & Legal Professionals",
  "Non-Disclosure Agreements Specialists",
  "Immigration Law Lawyers & Legal Professionals",
  "Compliance Specialists",
  "Civil Law Lawyers & Legal Professionals",
  "Regulatory Compliance Freelancers",
  "Family Law Lawyers & Legal Professionals",
  "Document Reviewers",
  "Litigation Specialists",
];
const LegalRoles = [
  "Real Estate Law Professionals",
  "Compliance Specialists",
  "Legal Consultants",
  "Family Law Professionals",
  "Legal Assistants",
  "Trademark Consultants",
  "Deposition Summary Specialists",
  "Workplace Safety & Health Professionals",
  "Arbitration Law Professionals",
  "Brand Licensing Professionals",
  "Bankruptcy Professionals",
  "Patent Law Professionals",
  "Medical Law Professionals",
  "Immigration Law Professionals",
  "Copyright Law Professionals",
  "Criminal Law Professionals",
  "Notaries",
  "Contract Drafters",
];
const LegalCrossFunctional = [
  "Legal Transcriptionist",
  "Legal Translators",
  "Section 508 Compliance Specialists",
  "Legal Writers",
  "Property Tax Specialists",
  "GDPR Freelancers",
  "Management Consultants",
  "Legal Researchers",
  "Fraud Analysts",
];
const LegalProjects = [
  "Translation Services",
  "Contracts & Agreement Writing",
  "Privay Policy Writing",
  "Terms of Service Writing",
  "Business & Corporate Legal Consulting",
  "Intellectual Property Consulting",
  "Tax Legal Consulting",
  "Commercial Legal Consulting",
  "Legal Assistance",
  "Cybersecurity & Data Protection Services",
  "Virtual Assistant Services",
];
const AllLegal = LegalPopular.concat(LegalRoles)
  .concat(LegalCrossFunctional)
  .concat(LegalProjects);

//HR & Training
const HRTrainingPopular = [
  "Technology Freelancers",
  "Recruiters & Recruitment Consultants",
  "Candidate sourcing Freelancers",
  "Interviewers",
  "LinkedIn Recruiters",
  "Human Resource Managers",
  "Boolean Search Specialists",
  "Technical Recruiters",
  "e-Learning Specialists",
  "Instructional Designers",
  "Online Freelancers",
  "Course Freelancers",
  "Learning Management System (LMS) Specialists",
  "Curriculum Developers",
  "Curriculum design Freelancers",
  "Training & Development Professionals",
  "Articulate Storyline Specialists",
  "Compensation Specialists",
  "Leadership Training Freelancers",
  "Organizational Development Consultant",
];
const HRTrainingRoles = [
  "Articulate Specialists",
  "Articulate Storyline Specialists",
  "Boolean Search Specialists",
  "Competencies Assessment Freelancers",
  "Curriculum Developers",
  "Distance Education Specialists",
  "Employee Engagement Specialists",
  "Executive Coaches",
  "HR Policies Specialists",
  "Interviewers",
  "ISO 9000 Specialists",
  "Job Description Writers",
  "Leadership Development Specialists",
  "LinkedIn Recruiters",
  "Onboarding Specialists",
  "Online Freelancers",
  "QHSE Specialists",
  "Recruiters & Recruitment Consultants",
  "Salary Surveys Specialists",
  "SAP SuccessFactors Freelancers",
  "SCORM Specialists",
  "Teachable Specialists",
  "Technical Recruiters",
];
const HRTrainingCrossFunctional = [
  "Applied Behavior Analysis (ABA) Professionals",
  "Business Coaches",
  "Business Innovation Freelancers",
  "Career Counselors",
  "Conflict Resolution Specialists",
  "Cross Functional Team Leadership Specialists",
  "Employent Law Lawyers & Legal Professionals",
  "Information Management Specialists",
  "International Business Specialists",
  "Lean Consultants",
  "Learning Management System (LMS) Specialists",
  "Legal Professionals",
  "LinkedIn API Developers",
  "Moodle Specialists",
  "Payroll Processing Specialists",
  "Resume Writers",
  "Revenue Management Freelancers",
];
const HRTrainingProjects = [
  "Accounting & Bookkeeping Services",
  "Business Consulting Services",
  "Cover Letter Writing Services",
  "eLearning Video Production Services",
  "Financial Consulting Services",
  "LinkedIn Profile Writing Services",
  "Project Management Services",
  "Resume Writing Services",
  "Virtual Assistant Services",
];

const AllHRTraining = HRTrainingPopular.concat(HRTrainingRoles)
  .concat(HRTrainingCrossFunctional)
  .concat(HRTrainingProjects);

//Engineer & Architecture
const EngineerArchitecturePopular = [
  "3D Designers",
  "3D Rendering Artists",
  "AutoCAD Drafters",
  "Architectural Designers",
  "Product Designers",
  "Sourcing Specialists",
  "Interior Designers",
  "Residential Freelancers",
  "Architectural Rendering Specialists",
  "2D Designers",
  "SketchUp Specialists",
  "Drafting Specialists",
  "Mechanical Engineers",
  "Electrical Engineers",
  "Floor Plan Designers",
  "CAD Designers",
  "Concept Design Specialists",
  "Logistics & Shipping Specialists",
  "Engineering Drawing Specialists",
  "Mathematics Specialists",
];
const EngineerArchitectureRoles = [
  "3D Printing Experts",
  "3D Rendering Artists",
  "AutoCAD Specialists",
  "Autodesk Fusion 360 Freelancers",
  "Biologists",
  "Chemists",
  "Contract Manufacturing Specialists",
  "Drafting Specialists",
  "Engineering Drawing Specialists",
  "Estimator Specialists",
  "Interior Designers",
  "Logistics & Shipping Specialists",
  "Mathematics Specialists",
  "PCB Designers",
  "Product Designers",
  "Robotics Engineers",
  "SketchUp Specialists",
  "SolidWorks Designers",
  "Sourcing Specialists",
  "Welders",
];
const EngineerArchitectureCrossFunctional = [
  "3D Designers & Artists",
  "Calculus Tutors & Teachers",
  "Game Designer",
  "Graphic Designer",
  "LaTeX Editors",
  "Photographer",
  "Project Managers",
  "Research Specialists",
  "Scientific Writers",
  "Section 508 Compliance Specialists",
  "Urban Designers",
  "Video Producers",
];
const EngineerArchitectureProjects = [
  "Architecture & Interior Design Consultation",
  "BIM 3D Modeling",
  "Packaging Design Services",
  "Product Manufacturing",
  "STEM Consultation & Tutoring",
  "Supplier & Vendor Sourcing",
  "Virtual Staging Services",
];
const AllEngineerArchitecture = EngineerArchitecturePopular.concat(
  EngineerArchitectureRoles
)
  .concat(EngineerArchitectureCrossFunctional)
  .concat(EngineerArchitectureProjects);

//ALL SKILLS
const AllSkills = AllDevelopmentIT.concat(AllCreativeDesign)
  .concat(AllSalesMarketing)
  .concat(AllWritingTranslation)
  .concat(AllAdminCustomer)
  .concat(AllFinanceAccounting)
  .concat(AllLegal)
  .concat(AllHRTraining)
  .concat(AllEngineerArchitecture);

const random = Math.floor(Math.random() * AllSkills.length);
console.log(random, AllSkills[random]);
